# This file is used by Google Cloud Build to build and deploy the Discord bot.

steps:
  # 1. Build the Docker image
  # Tag with both specific BUILD_ID and "latest"
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO/$_SERVICE_NAME:$BUILD_ID'
      - '-t'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO/$_SERVICE_NAME:latest'
      - '.'

  # 2. Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO/$_SERVICE_NAME'
      - '--all-tags'

images:
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO/$_SERVICE_NAME:$BUILD_ID'
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO/$_SERVICE_NAME:latest'

substitutions:
  _SERVICE_NAME: 'lotslarp-discord-bot'
  _REGION: 'us-east1'
  _ARTIFACT_REGISTRY_REPO: 'discord-bots'

options:
  machineType: 'E2_HIGHCPU_8'