[supervisord]
nodaemon=true

[program:discord_bot]
command=python3 /app/discord_bot.py
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/discord_bot.err.log
stdout_logfile=/var/log/discord_bot.out.log

[program:web_ui]
command=python3 /app/web_ui.py
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/web_ui.err.log
stdout_logfile=/var/log/web_ui.out.log